### ISSUE TITLE
1.17 Error

### ISSUE THREAD

**Issue by Geph** [whimc/Observations#25]
```
WARN java.sql.SQLSyntaxErrorException: Unknown column 'expiration' in 'where clause'
16.08 11:39:28 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
16.08 11:39:28 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
16.08 11:39:28 [Server] WARN at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1198)
16.08 11:39:28 [Server] WARN at WHIMC-Observations-2.2.1.jar//edu.whimc.observations.utils.sql.Queryer.lambda$loadObservations$4(Queryer.java:211)
16.08 11:39:28 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
16.08 11:39:28 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
16.08 11:39:28 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
16.08 11:39:28 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
16.08 11:39:28 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
16.08 11:39:28 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Geph** [comment]
I think this is fixed now

**Comment by Geph** [comment]
Yeah hasn't shown up since update and .schema file fix - closing
